import Banner from '@/components/Banner/Banner'
import BookCategory from '@/components/BookCategory/BookCategory'
import Allbook from '@/components/Books/Allbook'
import Image from 'next/image'

export const metadata = {
  title: 'Welcome to my Books Website',
  description: 'Generated by create next app',
}

export default function HomePage() {
  return (
    <main  >
      <Banner/>
      <BookCategory/>
    </main>
  )
}
