
import Allbook from '@/components/Books/Allbook';

export const metadata = {
    title: 'All books',
    description: 'Generated by create next app',
}

const allbookpage = () => {

    return (
        <div>
            <Allbook/>
        </div>
    );
};

export default allbookpage;